#!/usr/bin/env bash
#
# ergo-indexer — interactive setup
#
# Asks a handful of questions and writes a working ./indexer.toml.
# Start the indexer with:  ./ergo-indexer --config indexer.toml

set -euo pipefail

OUTPUT="./indexer.toml"

# ── Helpers ───────────────────────────────────────────────────────────
prompt() {
    local var="$1" question="$2" default="$3" reply=""
    read -r -p "${question} [${default}]: " reply
    printf -v "${var}" '%s' "${reply:-${default}}"
}

prompt_choice() {
    local var="$1" question="$2" default="$3" valid="$4" reply=""
    while true; do
        read -r -p "${question} [${default}]: " reply
        reply="${reply:-${default}}"
        if [[ "|${valid}|" == *"|${reply}|"* ]]; then
            printf -v "${var}" '%s' "${reply}"
            return
        fi
        echo "  ↳ must be one of: ${valid//|/, }"
    done
}

# ── Existing-config guard ─────────────────────────────────────────────
if [[ -e "${OUTPUT}" ]]; then
    echo "A config already exists at ${OUTPUT}."
    read -r -p "Overwrite? [y/N]: " reply
    case "${reply,,}" in
        y|yes) ;;
        *) echo "Aborted. Existing config left in place."; exit 0 ;;
    esac
fi

# ── Banner ────────────────────────────────────────────────────────────
cat <<'EOF'

ergo-indexer — interactive setup
────────────────────────────────
Press Enter to accept the bracketed default at each prompt.

The indexer needs a running ergo-node-rust to pull blocks from.

EOF

# ── Questions ─────────────────────────────────────────────────────────
prompt NODE_URL "Node HTTP API URL" "http://127.0.0.1:9052"

prompt_choice BACKEND "Database backend (sqlite/postgres)" "sqlite" "sqlite|postgres"

case "${BACKEND}" in
    sqlite)
        prompt DB_PATH "SQLite database file path" "./ergo-indexer-data/indexer.db"
        DB_URL="sqlite://${DB_PATH}"
        ;;
    postgres)
        echo "  ↳ Format: postgres://user:pass@host:port/dbname"
        echo "  ↳ PG* env vars (PGHOST, PGUSER, etc.) override matching components at connect time."
        prompt DB_URL "PostgreSQL connection URL" "postgres://localhost/ergo_indexer"
        ;;
esac

prompt API_BIND "REST API bind address" "127.0.0.1:8080"

echo "  ↳ Leave blank to resume from the highest indexed block (default)."
read -r -p "Override start height? []: " START_HEIGHT

# ── Write config ──────────────────────────────────────────────────────
{
    cat <<EOF
# Ergo Node Rust Indexer — generated by indexer-install.sh on $(date -u +"%Y-%m-%d %H:%M:%S UTC")
#
# Edit freely. For the full annotated reference (every supported
# option, with defaults), see ergo-indexer.toml.example.

[node]
url = "${NODE_URL}"

[storage]
db = "${DB_URL}"

[api]
bind = "${API_BIND}"
EOF

    if [[ -n "${START_HEIGHT}" ]]; then
        cat <<EOF

[sync]
start_height = ${START_HEIGHT}
EOF
    fi
} > "${OUTPUT}"

echo
echo "Wrote ${OUTPUT}."
echo
if [[ "${BACKEND}" == "sqlite" ]]; then
    DB_DIR=$(dirname "${DB_PATH}")
    if [[ "${DB_DIR}" != "." && ! -d "${DB_DIR}" ]]; then
        echo "Note: ${DB_DIR}/ will be created by the indexer on first run."
        echo
    fi
fi
echo "Start the indexer with:  ./ergo-indexer --config ${OUTPUT}"
echo
