#!/usr/bin/env bash
#
# ergo-node-rust — interactive setup
#
# Asks a handful of questions and writes a working ./ergo.toml in the
# current directory. Everything not asked here uses the binary's
# built-in defaults; see ergo.toml.example (shipped alongside this
# script) for the full annotated option set.

set -euo pipefail

OUTPUT="./ergo.toml"

# ── Helpers ───────────────────────────────────────────────────────────
prompt() {
    # prompt VAR_NAME "Question" "default"
    local var="$1" question="$2" default="$3" reply=""
    read -r -p "${question} [${default}]: " reply
    printf -v "${var}" '%s' "${reply:-${default}}"
}

prompt_choice() {
    # prompt_choice VAR_NAME "Question" "default" "valid|values|pipe-separated"
    local var="$1" question="$2" default="$3" valid="$4" reply=""
    while true; do
        read -r -p "${question} [${default}]: " reply
        reply="${reply:-${default}}"
        if [[ "|${valid}|" == *"|${reply}|"* ]]; then
            printf -v "${var}" '%s' "${reply}"
            return
        fi
        echo "  ↳ must be one of: ${valid//|/, }"
    done
}

# ── Existing-config guard ─────────────────────────────────────────────
if [[ -e "${OUTPUT}" ]]; then
    echo "A config already exists at ${OUTPUT}."
    read -r -p "Overwrite? [y/N]: " reply
    case "${reply,,}" in
        y|yes) ;;
        *) echo "Aborted. Existing config left in place."; exit 0 ;;
    esac
fi

# ── Banner ────────────────────────────────────────────────────────────
cat <<'EOF'

ergo-node-rust — interactive setup
──────────────────────────────────
Press Enter to accept the bracketed default at each prompt.

EOF

# ── Questions ─────────────────────────────────────────────────────────
prompt_choice NETWORK "Network (mainnet/testnet)" "testnet" "mainnet|testnet"
prompt_choice STATE_TYPE "State type (utxo/digest)" "utxo" "utxo|digest"
prompt DATA_DIR "Data directory" "./ergo-node-data"

if [[ "${STATE_TYPE}" == "utxo" ]]; then
    echo "  ↳ blocks_to_keep: -1 = full archival, 0 = at-tip only, N = retain last N blocks"
    prompt BLOCKS_TO_KEEP "Block history retention" "-1"
else
    BLOCKS_TO_KEEP="-1"  # ignored for digest, but kept for consistency in the file
fi

prompt CACHE_MB "redb cache size in MB (cold sync)" "256"
prompt FLUSH_HEAP "Live-heap flush threshold in MB (cold sync, 0 disables)" "4096"
prompt SYNCED_CACHE_MB "redb cache size in MB at tip (smaller = lower RSS)" "256"

case "${NETWORK}" in
    mainnet) DEFAULT_API="0.0.0.0:9052" ;;
    testnet) DEFAULT_API="0.0.0.0:9053" ;;
esac
prompt API_ADDRESS "REST API bind address" "${DEFAULT_API}"

# ── Network-specific peer + listen defaults ───────────────────────────
case "${NETWORK}" in
    mainnet)
        LISTEN_PORT="9030"
        SEED_PEERS=$(cat <<'EOF'
    "213.239.193.208:9030",
    "159.65.11.55:9030",
    "165.227.26.175:9030",
    "159.89.116.15:9030",
    "136.244.110.145:9030",
    "94.130.108.35:9030",
    "221.165.214.185:9030",
    "217.182.197.196:9030",
    "173.212.220.9:9030",
    "213.152.106.56:9030",
    "[2001:41d0:700:6662::]:29031",
EOF
        )
        ;;
    testnet)
        LISTEN_PORT="9030"
        SEED_PEERS=$(cat <<'EOF'
    "213.239.193.208:9023",
    "128.253.41.110:9020",
    "176.9.15.237:9021",
EOF
        )
        ;;
esac

# ── Write config ──────────────────────────────────────────────────────
cat > "${OUTPUT}" <<EOF
# Ergo Node Rust — generated by install.sh on $(date -u +"%Y-%m-%d %H:%M:%S UTC")
#
# Edit freely. For the full annotated option set (every supported
# field, with defaults), see ergo.toml.example.

[proxy]
network = "${NETWORK}"

[node]
data_dir = "${DATA_DIR}"
state_type = "${STATE_TYPE}"
blocks_to_keep = ${BLOCKS_TO_KEEP}
cache_mb = ${CACHE_MB}
flush_heap_threshold_mb = ${FLUSH_HEAP}
synced_cache_mb = ${SYNCED_CACHE_MB}
api_address = "${API_ADDRESS}"

[listen.ipv6]
address = "[::]:${LISTEN_PORT}"
mode = "full"
max_inbound = 20

[outbound]
min_peers = 3
max_peers = 10
seed_peers = [
${SEED_PEERS}
]

[identity]
agent_name = "ergo-node-rust"
peer_name = "ergo-node-rust"
protocol_version = "6.0.3"
EOF

echo
echo "Wrote ${OUTPUT}."
echo
echo "Start the node with:  ./ergo-node-rust"
echo
